import type { FoodItem } from './saju/types';

export const FOODS: FoodItem[] = [
  { id: 'mul-naengmyeon', name: '물냉면', emoji: '🍜', elements: ['water'] },
  { id: 'kong-guksu', name: '콩국수', emoji: '🥣', elements: ['water', 'earth'] },
  { id: 'mulhoe', name: '물회', emoji: '🐟', elements: ['water'] },
  { id: 'gul-gukbap', name: '굴국밥', emoji: '🦪', elements: ['water'] },
  { id: 'haemul-tang', name: '해물탕', emoji: '🦐', elements: ['water', 'fire'] },
  { id: 'sushi', name: '초밥', emoji: '🍣', elements: ['water', 'metal'] },
  { id: 'hoe-deopbap', name: '회덮밥', emoji: '🍚', elements: ['water', 'wood'] },
  { id: 'miyeok-guk', name: '미역국 정식', emoji: '🌊', elements: ['water'] },
  { id: 'kimchi-jjigae', name: '김치찌개', emoji: '🍲', elements: ['fire', 'earth'] },
  { id: 'maeun-tang', name: '매운탕', emoji: '🌶️', elements: ['fire', 'water'] },
  { id: 'buldak', name: '불닭', emoji: '🔥', elements: ['fire'] },
  { id: 'tteokbokki', name: '떡볶이', emoji: '🍢', elements: ['fire'] },
  { id: 'mala-tang', name: '마라탕', emoji: '🥘', elements: ['fire'] },
  { id: 'jeyuk-bokkeum', name: '제육볶음', emoji: '🥓', elements: ['fire', 'earth'] },
  { id: 'dak-galbi', name: '닭갈비', emoji: '🍗', elements: ['fire'] },
  { id: 'jjamppong', name: '짬뽕', emoji: '🍝', elements: ['fire', 'water'] },
  { id: 'bibimbap', name: '비빔밥', emoji: '🥗', elements: ['wood', 'earth'] },
  { id: 'salad-bowl', name: '샐러드볼', emoji: '🥬', elements: ['wood'] },
  { id: 'ssambap', name: '쌈밥', emoji: '🥬', elements: ['wood', 'earth'] },
  { id: 'bibim-guksu', name: '비빔국수', emoji: '🍜', elements: ['wood', 'fire'] },
  { id: 'wolnam-ssam', name: '월남쌈', emoji: '🌯', elements: ['wood', 'water'] },
  { id: 'tomato-pasta', name: '토마토 파스타', emoji: '🍝', elements: ['fire', 'wood'] },
  { id: 'cream-pasta', name: '크림 파스타', emoji: '🥛', elements: ['metal', 'earth'] },
  { id: 'donkatsu', name: '돈까스', emoji: '🍱', elements: ['earth', 'metal'] },
  { id: 'curry-rice', name: '카레라이스', emoji: '🍛', elements: ['earth', 'fire'] },
  { id: 'gimbap', name: '김밥', emoji: '🍙', elements: ['earth', 'wood'] },
  { id: 'baekban', name: '백반정식', emoji: '🍚', elements: ['earth'] },
  { id: 'sundubu', name: '순두부찌개', emoji: '🥘', elements: ['earth', 'fire'] },
  { id: 'galbi-tang', name: '갈비탕', emoji: '🍖', elements: ['earth', 'water'] },
  { id: 'seolleong-tang', name: '설렁탕', emoji: '🥛', elements: ['water', 'metal'] },
  { id: 'samgye-tang', name: '삼계탕', emoji: '🐔', elements: ['earth', 'water'] },
  { id: 'bossam', name: '보쌈정식', emoji: '🥩', elements: ['earth', 'water'] },
  { id: 'chicken', name: '치킨', emoji: '🍗', elements: ['fire', 'metal'] },
  { id: 'burger', name: '수제버거', emoji: '🍔', elements: ['fire', 'earth'] },
  { id: 'pizza', name: '피자', emoji: '🍕', elements: ['fire', 'earth'] },
  { id: 'pho', name: '쌀국수', emoji: '🍜', elements: ['water', 'wood'] },
  { id: 'udon', name: '우동', emoji: '🍲', elements: ['water', 'earth'] },
  { id: 'soba', name: '메밀소바', emoji: '🥢', elements: ['wood', 'water'] },
  { id: 'tendon', name: '텐동', emoji: '🍤', elements: ['metal', 'earth'] },
  { id: 'gyudon', name: '규동', emoji: '🥩', elements: ['earth', 'metal'] },
  { id: 'jajangmyeon', name: '짜장면', emoji: '🍜', elements: ['earth', 'fire'] },
  { id: 'tangsuyuk', name: '탕수육', emoji: '🍖', elements: ['metal', 'fire'] },
  { id: 'sandwich', name: '샌드위치', emoji: '🥪', elements: ['wood', 'metal'] },
  { id: 'poke', name: '포케', emoji: '🥗', elements: ['water', 'wood'] },
];
